### ISSUE TITLE
How to tune hyperparameter when use the lambdamart example

### ISSUE THREAD

**Issue by hbghhy** [acbull/Unbiased_LambdaMart#4]
I have read the paper and the train.conf file in the lambdarank. It seems there are some hyperparameter such as p and M in the paper. But I cannot find it in the train.conf. Do I miss something?

And I want to use the lib in a large-scale dataset. Train lgb M times will cost a lot time. Can we just train some weak lgb at begining to estimate position-baised parameter. And then re-train with a complex lgb. Did you try it?

**Comment by acbull** [comment]
There are mainly two hyper-parameters that can be tuned, which is all in the src/objective/rank_objective.hpp files. They are:

```
  double _eta               : this denotes how much regularization is posed to the position bias.
  size_t _position_bins     : this denotes the maximum positions taken into account.
```

If you want to re-implement the result of our table, you can change the regularization term back to 0, by modifying 
```
double _eta = 1.0 / (1 + 0.5); 
```
in the src/objective/rank_objective.hpp (Line 418) to 
```
double _eta = 1.0 / (1 + 0); 
```

**Comment by hbghhy** [comment]
THX.
