### ISSUE TITLE
Add LICENSE.md to project root

### ISSUE THREAD

**Issue by paddy74** [acbull/Unbiased_LambdaMart#5]
As a publically viewable project, Unbiased_LambdaMart should include a LICENSE.md file in order to explicitly convey how this project may be used.
As an unlicensed repository, the only rights provided to other users are to view and fork the repository. This is not in line with any desire for this work to be utilized in other projects.

Coming from [GitHub's licensing help page](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> You're under no obligation to choose a license. It's your right not to
> include one with your code or project, but please be aware of the
> implications. Generally speaking, the absence of a license means that
> the default copyright laws apply. This means that you retain all
> rights to your source code and that nobody else may reproduce,
> distribute, or create derivative works from your work. This might not
> be what you intend.
> 
> Even if this is what you intend, if you publish your source code in a
> public repository on GitHub, you have accepted the Terms of Service
> which do allow other GitHub users some rights. Specifically, you allow
> others to view and fork your repository.
> 
> If you want to share your work with others, we strongly encourage you
> to include an open source license.

I would strongly recommend the [MIT license](https://opensource.org/licenses/MIT) to encourage the widest availability of this project to other researchers, or if you seek protections regarding promotion and advertising material the BSD 3-clause, or Apache 2.0 if you want MIT with more words.

It also appears at first glance that the project is licensed under MIT, as that is the license included in the Unbias_LightGBM directory. However, it is not entirely clear as that is also the license provided with LightGBM.

**Comment by acbull** [comment]
Done~ Have added the MIT license as suggested. Thanks so much for the advice.
